### ISSUE TITLE
Error file is a directory (cache)

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#200]
Hi @kevinushey,

Hope you are well. 

Just wanted to flag an error that i seem to be getting with renv that i would've expected from experience was resolved by now. 

The error is as follows:

```
* Querying repositories for available binary packages ... Done!
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.5/lattice_0.20-38.zip' ...
	OK [downloaded 1.1 Mb in 0.3 secs]
Error: file 'C:/Agents/renv/v4/R-3.5/x86_64-w64-mingw32/MASS/7.3-51.1/9beca15f32d56f1a5eacfa6419948eb9/MASS' is a directory.
Traceback (most recent calls first):
15: source(Sys.getenv("BUILD_ANALYSIS_R_SCRIPT"), local = TRUE)
14: withVisible(eval(ei, envir))
13: eval(ei, envir)
12: eval(ei, envir)
11: renv::restore()
10: renv_restore_run_actions(project, diff, current, lockfile)
 9: renv_retrieve(packages)
 8: handler(package, renv_retrieve_impl(package))
 7: renv_retrieve_impl(package)
 6: renv_retrieve_successful(record, path)
 5: renv_description_read(path, subdir = subdir)
 4: renv_filebacked("DESCRIPTION", path, renv_description_read_impl, 
        subdir = subdir, ...)
 3: callback(path, ...)
 2: stopf("file '%s' is a directory.", path)
 1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
```

And is just in a general build pipeline that is restoring an renv environment. 

It seems to be having problems with packages already being in the cache.

Any ideas what this is about?

Regards,

Adam

**Comment by kevinushey** [comment]
Does this directory exist?

> C:/Agents/renv/v4/R-3.5/x86_64-w64-mingw32/MASS/7.3-51.1/9beca15f32d56f1a5eacfa6419948eb9/MASS

If so, what does it contain? Does it appear to be a real, installed package?

**Comment by adamrobinson361** [comment]
Hi Kevin - its actually an empty folder. I'm pretty sure the previous package I tested wasn't an empty folder. 

Can you test for empty folder and delete if empty in restore?

**Comment by kevinushey** [comment]
That is indeed what we're doing now on master. This should be fixed now; please feel free to re-open if you're still bumping into issues.

**Comment by adamrobinson361** [comment]
Hi @kevinushey - the issue still persists for me on latest version. I can attach some wider logs if that helps?

**Comment by adamrobinson361** [comment]
See below - it looks to be occurring at the downloading of packages stage?

```
019-09-30T16:02:02.1653946Z [1] ""
2019-09-30T16:02:02.1654417Z [1] "Installing latest version of renv"
2019-09-30T16:02:02.1654549Z [1] ""
2019-09-30T16:02:02.9501776Z Downloading GitHub repo rstudio/renv@master
2019-09-30T16:02:09.6740025Z Running `R CMD build`...
2019-09-30T16:02:11.9789515Z * checking for file 'C:\Users\svc-VSTSBldAge-EFABL\AppData\Local\Temp\RtmpwL2s6n\remotes1a5470c03bc3\rstudio-renv-24ed969/DESCRIPTION' ... OK
2019-09-30T16:02:11.9790109Z * preparing 'renv':
2019-09-30T16:02:11.9790265Z * checking DESCRIPTION meta-information ... OK
2019-09-30T16:02:11.9790383Z * checking for LF line-endings in source and make files and shell scripts
2019-09-30T16:02:11.9790451Z * checking for empty or unneeded directories
2019-09-30T16:02:11.9790508Z * building 'renv_0.7.0-117.tar.gz'
2019-09-30T16:02:12.7562623Z * installing *source* package 'renv' ...
2019-09-30T16:02:12.8890922Z ** R
2019-09-30T16:02:13.0108332Z ** inst
2019-09-30T16:02:13.0189831Z ** byte-compile and prepare package for lazy loading
2019-09-30T16:02:18.6984229Z ** help
2019-09-30T16:02:18.9368822Z *** installing help indices
2019-09-30T16:02:19.0508341Z   converting help for package 'renv'
2019-09-30T16:02:19.0859726Z     finding HTML links ... done
2019-09-30T16:02:19.1199002Z     activate                                html  
2019-09-30T16:02:19.1421797Z     bootstrap                               html  
2019-09-30T16:02:19.1559349Z     clean                                   html  
2019-09-30T16:02:19.2006939Z     config                                  html  
2019-09-30T16:02:19.2164903Z     consent                                 html  
2019-09-30T16:02:19.2291476Z     deactivate                              html  
2019-09-30T16:02:19.2573337Z     dependencies                            html  
2019-09-30T16:02:19.2638073Z     equip                                   html  
2019-09-30T16:02:19.2754355Z     history                                 html  
2019-09-30T16:02:19.3023310Z     hydrate                                 html  
2019-09-30T16:02:19.3432533Z     init                                    html  
2019-09-30T16:02:19.3673785Z     install                                 html  
2019-09-30T16:02:19.3766460Z     isolate                                 html  
2019-09-30T16:02:19.3878255Z     load                                    html  
2019-09-30T16:02:19.4227133Z     lockfile                                html  
2019-09-30T16:02:19.4409417Z     migrate                                 html  
2019-09-30T16:02:19.4496258Z     modify                                  html  
2019-09-30T16:02:19.4989851Z     paths                                   html  
2019-09-30T16:02:19.5062893Z     project                                 html  
2019-09-30T16:02:19.5233044Z     purge                                   html  
2019-09-30T16:02:19.5418380Z     rebuild                                 html  
2019-09-30T16:02:19.5516924Z     refresh                                 html  
2019-09-30T16:02:19.5583245Z     remote                                  html  
2019-09-30T16:02:19.5707889Z     remove                                  html  
2019-09-30T16:02:19.5856311Z     renv-package                            html  
2019-09-30T16:02:19.6143613Z     restore                                 html  
2019-09-30T16:02:19.6293825Z     revert                                  html  
2019-09-30T16:02:19.6467862Z     run                                     html  
2019-09-30T16:02:19.6778392Z     settings                                html  
2019-09-30T16:02:19.7236700Z     snapshot                                html  
2019-09-30T16:02:19.7375719Z     status                                  html  
2019-09-30T16:02:19.7591931Z     update                                  html  
2019-09-30T16:02:19.7782747Z     upgrade                                 html  
2019-09-30T16:02:19.8097359Z     use_python                              html  
2019-09-30T16:02:19.8106167Z ** building package indices
2019-09-30T16:02:19.9158601Z ** installing vignettes
2019-09-30T16:02:19.9245208Z ** testing if installed package can be loaded
2019-09-30T16:02:19.9247959Z *** arch - i386
2019-09-30T16:02:20.2430182Z *** arch - x64
2019-09-30T16:02:20.5652745Z * DONE (renv)
2019-09-30T16:02:20.7851573Z In R CMD INSTALL
2019-09-30T16:02:20.9191087Z [1] ""
2019-09-30T16:02:20.9191979Z [1] "Restoring renv environment"
2019-09-30T16:02:20.9192046Z [1] ""
2019-09-30T16:02:30.6448290Z * Querying repositories for available binary packages ... Done!
2019-09-30T16:02:33.4935855Z A new version of the renv package will be installed:
2019-09-30T16:02:33.4936122Z 
2019-09-30T16:02:33.4980958Z # GitHub =============================
2019-09-30T16:02:33.4986968Z - renv   [0.7.0-108 -> rstudio/renv]
2019-09-30T16:02:33.4987901Z 
2019-09-30T16:02:33.4988050Z This project will use the newly-installed version of renv.
2019-09-30T16:02:33.4988372Z 
2019-09-30T16:02:33.5755705Z Installing renv [0.7.0-117] ...
2019-09-30T16:02:33.5778535Z 	OK (linked cache)
2019-09-30T16:02:33.8622034Z * renv upgraded -- please restart the R session.
2019-09-30T16:02:33.8625305Z                       CRAN 
2019-09-30T16:02:33.8625399Z "https://cran.rstudio.com" 
2019-09-30T16:02:34.1504823Z The following package(s) will be updated:
2019-09-30T16:02:34.1505033Z 
2019-09-30T16:02:34.1565150Z # CRAN ===============================
2019-09-30T16:02:34.1568643Z - lattice        [0.20-35 -> 0.20-38]
2019-09-30T16:02:34.1568825Z - MASS           [7.3-50 -> 7.3-51.1]
2019-09-30T16:02:34.1568900Z - Matrix         [1.2-14 -> 1.2-15]
2019-09-30T16:02:34.1569037Z - mgcv           [1.8-24 -> 1.8-27]
2019-09-30T16:02:34.1569086Z - BH             [* -> 1.69.0-1]
2019-09-30T16:02:34.1569135Z - DT             [* -> 0.9]
2019-09-30T16:02:34.1569204Z - R6             [* -> 2.4.0]
2019-09-30T16:02:34.1569253Z - RColorBrewer   [* -> 1.1-2]
2019-09-30T16:02:34.1569328Z - RODBC          [* -> 1.3-16]
2019-09-30T16:02:34.1569377Z - Rcpp           [* -> 1.0.2]
2019-09-30T16:02:34.1569424Z - askpass        [* -> 1.1]
2019-09-30T16:02:34.1569471Z - assertthat     [* -> 0.2.1]
2019-09-30T16:02:34.1569733Z - backports      [* -> 1.1.4]
2019-09-30T16:02:34.1569782Z - base64enc      [* -> 0.1-3]
2019-09-30T16:02:34.1569830Z - brew           [* -> 1.0-6]
2019-09-30T16:02:34.1569879Z - callr          [* -> 3.3.1]
2019-09-30T16:02:34.1569927Z - cli            [* -> 1.1.0]
2019-09-30T16:02:34.1569976Z - clipr          [* -> 0.7.0]
2019-09-30T16:02:34.1570041Z - clisymbols     [* -> 1.2.0]
2019-09-30T16:02:34.1570090Z - colorspace     [* -> 1.4-1]
2019-09-30T16:02:34.1570415Z - commonmark     [* -> 1.7]
2019-09-30T16:02:34.1570466Z - covr           [* -> 3.3.1]
2019-09-30T16:02:34.1570514Z - crayon         [* -> 1.3.4]
2019-09-30T16:02:34.1570580Z - crosstalk      [* -> 1.0.0]
2019-09-30T16:02:34.1570628Z - curl           [* -> 4.0]
2019-09-30T16:02:34.1570734Z - desc           [* -> 1.2.0]
2019-09-30T16:02:34.1570783Z - devtools       [* -> 2.2.0]
2019-09-30T16:02:34.1570832Z - digest         [* -> 0.6.21]
2019-09-30T16:02:34.1570897Z - dplyr          [* -> 0.8.3]
2019-09-30T16:02:34.1570947Z - ellipsis       [* -> 0.2.0.1]
2019-09-30T16:02:34.1570995Z - evaluate       [* -> 0.14]
2019-09-30T16:02:34.1571044Z - fansi          [* -> 0.4.0]
2019-09-30T16:02:34.1571092Z - fs             [* -> 1.3.1]
2019-09-30T16:02:34.1571141Z - ggplot2        [* -> 3.2.1]
2019-09-30T16:02:34.1571209Z - gh             [* -> 1.0.1]
2019-09-30T16:02:34.1571257Z - git2r          [* -> 0.26.1]
2019-09-30T16:02:34.1571306Z - glue           [* -> 1.3.1]
2019-09-30T16:02:34.1571364Z - gtable         [* -> 0.3.0]
2019-09-30T16:02:34.1571412Z - highr          [* -> 0.8]
2019-09-30T16:02:34.1571477Z - hms            [* -> 0.5.1]
2019-09-30T16:02:34.1571525Z - htmltools      [* -> 0.3.6]
2019-09-30T16:02:34.1571574Z - htmlwidgets    [* -> 1.3]
2019-09-30T16:02:34.1571622Z - httpuv         [* -> 1.5.2]
2019-09-30T16:02:34.1571682Z - httr           [* -> 1.4.1]
2019-09-30T16:02:34.1571729Z - ini            [* -> 0.3.1]
2019-09-30T16:02:34.1571795Z - jsonlite       [* -> 1.6]
2019-09-30T16:02:34.1571844Z - knitr          [* -> 1.24]
2019-09-30T16:02:34.1571892Z - labeling       [* -> 0.3]
2019-09-30T16:02:34.1571940Z - later          [* -> 0.8.0]
2019-09-30T16:02:34.1571988Z - lazyeval       [* -> 0.2.2]
2019-09-30T16:02:34.1572036Z - lubridate      [* -> 1.7.4]
2019-09-30T16:02:34.1572104Z - magrittr       [* -> 1.5]
2019-09-30T16:02:34.1572152Z - markdown       [* -> 1.1]
2019-09-30T16:02:34.1572200Z - memoise        [* -> 1.1.0]
2019-09-30T16:02:34.1572247Z - mime           [* -> 0.7]
2019-09-30T16:02:34.1572306Z - munsell        [* -> 0.5.0]
2019-09-30T16:02:34.1572369Z - openssl        [* -> 1.4.1]
2019-09-30T16:02:34.1572418Z - pillar         [* -> 1.4.2]
2019-09-30T16:02:34.1572465Z - pkgbuild       [* -> 1.0.5]
2019-09-30T16:02:34.1572513Z - pkgconfig      [* -> 2.0.2]
2019-09-30T16:02:34.1572705Z - pkgload        [* -> 1.0.2]
2019-09-30T16:02:34.1572973Z - plogr          [* -> 0.2.0]
2019-09-30T16:02:34.1573037Z - plyr           [* -> 1.8.4]
2019-09-30T16:02:34.1573083Z - praise         [* -> 1.0.0]
2019-09-30T16:02:34.1573129Z - prettyunits    [* -> 1.0.2]
2019-09-30T16:02:34.1573176Z - processx       [* -> 3.4.1]
2019-09-30T16:02:34.1573221Z - promises       [* -> 1.0.1]
2019-09-30T16:02:34.1573267Z - ps             [* -> 1.3.0]
2019-09-30T16:02:34.1573332Z - purrr          [* -> 0.3.2]
2019-09-30T16:02:34.1573379Z - rcmdcheck      [* -> 1.3.3]
2019-09-30T16:02:34.1573425Z - readr          [* -> 1.3.1]
2019-09-30T16:02:34.1573470Z - remotes        [* -> 2.1.0]
2019-09-30T16:02:34.1573527Z - reshape2       [* -> 1.4.3]
2019-09-30T16:02:34.1573589Z - rex            [* -> 1.1.2]
2019-09-30T16:02:34.1573635Z - rlang          [* -> 0.4.0]
2019-09-30T16:02:34.1573681Z - rmarkdown      [* -> 1.15]
2019-09-30T16:02:34.1573727Z - roxygen2       [* -> 6.1.1]
2019-09-30T16:02:34.1573782Z - rprojroot      [* -> 1.3-2]
2019-09-30T16:02:34.1574007Z - rstudioapi     [* -> 0.10]
2019-09-30T16:02:34.1574071Z - rversions      [* -> 2.0.0]
2019-09-30T16:02:34.1574118Z - scales         [* -> 1.0.0]
2019-09-30T16:02:34.1574166Z - sessioninfo    [* -> 1.1.1]
2019-09-30T16:02:34.1574214Z - shiny          [* -> 1.3.2]
2019-09-30T16:02:34.1574617Z - sourcetools    [* -> 0.1.7]
2019-09-30T16:02:34.1574683Z - stringi        [* -> 1.4.3]
2019-09-30T16:02:34.1574758Z - stringr        [* -> 1.4.0]
2019-09-30T16:02:34.1574810Z - sys            [* -> 3.2]
2019-09-30T16:02:34.1574864Z - testthat       [* -> 2.2.1]
2019-09-30T16:02:34.1574917Z - tibble         [* -> 2.1.3]
2019-09-30T16:02:34.1575103Z - tidyselect     [* -> 0.2.5]
2019-09-30T16:02:34.1575176Z - tinytex        [* -> 0.16]
2019-09-30T16:02:34.1575233Z - usethis        [* -> 1.5.1]
2019-09-30T16:02:34.1575337Z - utf8           [* -> 1.1.4]
2019-09-30T16:02:34.1575390Z - vctrs          [* -> 0.2.0]
2019-09-30T16:02:34.1575458Z - viridisLite    [* -> 0.3.0]
2019-09-30T16:02:34.1575511Z - whisker        [* -> 0.4]
2019-09-30T16:02:34.1575584Z - withr          [* -> 2.1.2]
2019-09-30T16:02:34.1575637Z - xfun           [* -> 0.9]
2019-09-30T16:02:34.1575689Z - xml2           [* -> 1.2.2]
2019-09-30T16:02:34.1575742Z - xopen          [* -> 1.0.0]
2019-09-30T16:02:34.1575796Z - xtable         [* -> 1.8-4]
2019-09-30T16:02:34.1575849Z - yaml           [* -> 2.2.0]
2019-09-30T16:02:34.1575921Z - zeallot        [* -> 0.1.0]
2019-09-30T16:02:34.1575959Z 
2019-09-30T16:02:34.1576034Z # GitHub =============================
2019-09-30T16:02:34.1576095Z - dfeR           [* -> dfe-analytical-services/dfeR]
2019-09-30T16:02:34.1576148Z 
2019-09-30T16:02:34.1733011Z Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.5/lattice_0.20-38.zip' ...
2019-09-30T16:02:34.1770591Z 	OK [file is up to date]
2019-09-30T16:02:34.2121868Z Retrieving 'https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-51.1.tar.gz' ...
2019-09-30T16:02:34.4612027Z 	OK [file is up to date]
2019-09-30T16:02:35.3287509Z Retrieving 'https://cran.rstudio.com/src/contrib/Archive/Matrix/Matrix_1.2-15.tar.gz' ...
2019-09-30T16:02:35.6114586Z 	OK [file is up to date]
2019-09-30T16:02:37.3055955Z Error: file 'C:/Agents/renv/v4/R-3.5/x86_64-w64-mingw32/mgcv/1.8-27/722a75e0bb49aaf187e1121e3481efe9/mgcv' is a directory.
2019-09-30T16:02:37.3071864Z Traceback (most recent calls first):
2019-09-30T16:02:37.3072310Z 15: source(Sys.getenv("BUILD_ANALYSIS_R_SCRIPT"), local = TRUE)
2019-09-30T16:02:37.3072378Z 14: withVisible(eval(ei, envir))
2019-09-30T16:02:37.3072486Z 13: eval(ei, envir)
2019-09-30T16:02:37.3072543Z 12: eval(ei, envir)
2019-09-30T16:02:37.3072643Z 11: renv::restore()
2019-09-30T16:02:37.3072704Z 10: renv_restore_run_actions(project, diff, current, lockfile)
2019-09-30T16:02:37.3072762Z  9: renv_retrieve(packages)
2019-09-30T16:02:37.3072821Z  8: handler(package, renv_retrieve_impl(package))
2019-09-30T16:02:37.3073192Z  7: renv_retrieve_impl(package)
2019-09-30T16:02:37.3073250Z  6: renv_retrieve_successful(record, path)
2019-09-30T16:02:37.3073310Z  5: renv_description_read(path, subdir = subdir)
2019-09-30T16:02:37.3073428Z  4: renv_filebacked("DESCRIPTION", path, renv_description_read_impl, 
2019-09-30T16:02:37.3073486Z         subdir = subdir, ...)
2019-09-30T16:02:37.3073560Z  3: callback(path, ...)
2019-09-30T16:02:37.3073617Z  2: stopf("file '%s' is a directory.", path)
2019-09-30T16:02:37.3073675Z  1: stop(sprintf(fmt, ...), call. = call.)
2019-09-30T16:02:37.3087338Z Execution halted
2019-09-30T16:02:37.5897056Z ##[error]PowerShell exited with code '1'.
2019-09-30T16:02:37.6210875Z ##[section]Finishing: PowerShell Script
```

**Comment by kevinushey** [comment]
Are you sure you're using the latest version of `renv`? See from the build log:

```
2019-09-30T16:02:33.4935855Z A new version of the renv package will be installed:
2019-09-30T16:02:33.4936122Z 
2019-09-30T16:02:33.4980958Z # GitHub =============================
2019-09-30T16:02:33.4986968Z - renv   [0.7.0-108 -> rstudio/renv]
2019-09-30T16:02:33.4987901Z 
2019-09-30T16:02:33.4988050Z This project will use the newly-installed version of renv.
2019-09-30T16:02:33.4988372Z 
2019-09-30T16:02:33.5755705Z Installing renv [0.7.0-117] ...
2019-09-30T16:02:33.5778535Z 	OK (linked cache)
2019-09-30T16:02:33.8622034Z * renv upgraded -- please restart the R session.
```

Note that the upgraded version of `renv` won't be used until you restart R.

**Comment by adamrobinson361** [comment]
Hmmm potentially not then - I'll be able to check tomorrow with a manual upgrade locally and push to git. 

On a workflow note, how would you recommend handling updates to renv in a DevOps pipeline? I'd like to use the latest renv for now regardless of the version associated with the project. The restart method doesn't seem great for a single script pipeline solution

**Comment by kevinushey** [comment]
> On a workflow note, how would you recommend handling updates to renv in a DevOps pipeline? I'd like to use the latest renv for now regardless of the version associated with the project. The restart method doesn't seem great for a single script pipeline solution

It's probably possible to unload and reload `renv` after a new copy is installed. I'll see if I can make that happen.

**Comment by kevinushey** [comment]
Okay, you might want to give it another shot with latest `renv` on master.

**Comment by adamrobinson361** [comment]
That seems to have done the trick. Note this does require updating renv
first as the no restart upgrade will be from this version forwards if my
understanding is correct.

Thanks for the fix!

Adam

**Comment by kevinushey** [comment]
Phew! Glad to hear everything is working as expected.

Note that I also added the auto-reload with `renv::upgrade()`, so you should see the latest version of `renv` installed get used after calling that (even without restarting R).
