### ISSUE TITLE
renv::restore does not resolve packages on self-hosted Gitlab instances when using `pak`

### ISSUE THREAD

**Issue by sklas** [rstudio/renv#2180]
Hi,
I tried to switch to `pak` for package installation with renv. 
We use a self-hosted Gitlab instance for internal package development and do also have several packages as dependencies on a self-hosted Gitlab instance.
`renv::restore` is used regularly in Gitlab CI pipelines to check/test and also create docker images.
Restoring packages hosted on that Gitlab instance does not work when using `pak` and the packages are installed via `remotes::install_gitlab()` or similar approaches, but they do work when installing directly from git repositories. 
I did also open an issue in the `pak` repo: https://github.com/r-lib/pak/issues/820

**Comment by kevinushey** [comment]
Can you please provide a reproducible example? I made this change in the development version which might help with things, but it's hard to know for sure.

https://github.com/rstudio/renv/commit/1d387f32453636f240f46d4a866fe3116028206e

The following example works for me using the development version of `renv`:

```R
# initialize project
renv::init()

# install package from gitlab, add to lockfile
renv::install("gitlab::renv-group/package")
writeLines("library(package)", con = "_deps.R")
renv::snapshot()

# try to remove and restore with pak
options(renv.config.pak.enabled = TRUE)
remove.packages("package")
renv::restore(rebuild = TRUE)
```

It would be helpful if you could include the error log you're seeing from `renv::restore()` as well.

**Comment by sklas** [comment]
Your example works well, also with the released version. I am struggling with a reproducible example, as I don't know a self-hosted Gitlab instance which is publicly available, so I need to stick to sharing my logs/files.

When hosting the package on our gitlab I can install it with: `renv::install("gitlab@gitlab.<url>.de::bioinf/rlib/testpackage")`, but only when `options(renv.config.pak.enabled = FALSE)`.
If I enable pak then its aborting with this message: 

```
> renv::install("gitlab@gitlab.<url>.de::bioinf/rlib/testpackage")
Error: 
! error in pak subprocess
Caused by error in `get_remote_types(refs)`:
! Cannot parse package:
gitlab@gitlab.<url>.de::bioinf/rlib/testpackage.
ℹ See `?pkgdepends::pkg_refs()` for supported package sources.
Type .Last.error to see the more details.
Traceback (most recent calls last):
6: renv::install("gitlab@gitlab.<url>.de::bioinf/rlib/testpackage")
5: renv_pak_install(packages = packages, library = libpaths, type = type, 
       rebuild = rebuild, prompt = prompt, project = project)
4: pak$pkg_install(pkg = packages, lib = library[[1L]], ask = prompt, 
       upgrade = TRUE)
3: remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), 
       list(pkg = pkg, lib = lib, upgrade = upgrade, ask = ask, 
           start = start, dependencies = dependencies, loaded = loaded_packages(lib)))
2: err$throw(res$error)
1: base::stop(cond)
```
This is not a real problem, as I can just install it directly with the `remotes` package or use syntax suggested for `pak` 
```
renv::install("gitlab::https://gitlab.<url>.de/bioinf/rlib/testpackage")
```


When I snapshot the package I get this entry in the lockfile:
```
 "package": {
      "Package": "package",
      "Version": "0.0.0.9000",
      "Source": "GitLab",
      "Title": "What the Package Does (One Line, Title Case)",
      "Authors@R": "person(\"Kevin\", \"Ushey\", , \"kevinushey@gmail.com\", role = c(\"aut\", \"cre\"), comment = c(ORCID = \"0000-0003-2880-7407\"))",
      "Description": "What the package does (one paragraph).",
      "License": "`use_mit_license()`, `use_gpl3_license()` or friends to pick a license",
      "Encoding": "UTF-8",
      "Roxygen": "list(markdown = TRUE)",
      "RoxygenNote": "7.3.3",
      "Author": "Kevin Ushey [aut, cre] (<https://orcid.org/0000-0003-2880-7407>)",
      "Maintainer": "Kevin Ushey <kevinushey@gmail.com>",
      "RemoteType": "gitlab",
      "RemoteHost": "gitlab.<url>.de",
      "RemoteUsername": "bioinf",
      "RemoteRepo": "rlib/testpackage",
      "RemoteSubdir": "",
      "RemoteRef": "main",
      "RemoteSha": "babda05db8146b37a552c77651e2cd084a05ce98"
    }
```
And on restore with enabled `pak` I see this error message:
```
> renv::restore(rebuild = TRUE)
✔ Loading metadata database ... done                                    
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* package=gitlab::bioinf/rlib/testpackage/@babda05db8146b37a552c77651e2cd084a05ce98: ! pkgdepends resolution error for
package=gitlab::bioinf/rlib/testpackage/@babda05db8146b37a552c77651e2cd084a05ce98.
Caused by error: 
! missing value where TRUE/FALSE needed
* remotes@2.5.0: dependency conflict
Type .Last.error to see the more details.
Traceback (most recent calls last):
6: renv::restore(rebuild = TRUE)
5: renv_pak_restore(lockfile = lockfile, packages = packages, exclude = exclude, 
       prompt = prompt, project = project)
4: pak$pkg_install(pkg = remotes, ask = prompt)
3: remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), 
       list(pkg = pkg, lib = lib, upgrade = upgrade, ask = ask, 
           start = start, dependencies = dependencies, loaded = loaded_packages(lib)))
2: err$throw(res$error)
1: base::stop(cond)
```
Note that I did not remove the exact URL here as I did in the examples before. This error message is unchanged.
It looks like `renv::restore` is ignoring the `RemoteHost` argument from the lockfile entry.

**Comment by kevinushey** [comment]
Thanks -- I've pushed a candidate fix for `renv` here. Can you install it with

```R
renv::install("rstudio/renv")
```

then restart your session, and try your test again to see if it helps?

**Comment by JamieCranston** [comment]
Issue still occurs for me on
`packageVersion("renv")
[1] ‘1.2.3’
`

+ Rscript -e 'options(renv.consent = TRUE, renv.config.pak.enabled = TRUE)' -e 'renv::restore()'
Error:
  ! error in pak subprocess
Caused by error in `get_remote_types(refs)`:
  ! Cannot parse package:
  gitlab@gitlab.<url>::<project>/<repo>@<SHA>.
ℹ See `?pkgdepends::pkg_refs()` for supported package sources.

**Comment by JamieCranston** [comment]
Running pkgdepends::parse_pkg_refs() directly reproduces the error message so think renv is generating an invalid ref?
