### ISSUE TITLE
deactivate leave the renv project library in libPaths

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#219]
Hi, 

While doing some test on renv on rstudio server I encounter this behavior. 

* When a project is initialized the infrastructure is created and R session restarted automatically
* `.libPaths` is correctly modified with project lib and renv system lib.
* If then I deactivate renv, files are updated, and R session is automatically restarted. However, in the new R console, the old libraries are correctly restored except the user library which is still `renv` project lib and not my user library from `R_LIBS_USER` environment variable.

See below for the step and output

```r
> .libPaths()
[1] "/home/bureau.si.interne/dervieuxchr/R/library"    "/applis/R/site-library/x86_64-pc-linux-gnu/3.5.1"
[3] "/opt/R/3.5.1/lib64/R/library"                    
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Lockfile written to '~/testR/test-renv/renv.lock'.

Restarting R session...

* Project '~/testR/test-renv' loaded. [renv 0.7.1-20]
> .libPaths()
[1] "/home/bureau.si.interne/dervieuxchr/testR/test-renv/renv/library/R-3.5/x86_64-pc-linux-gnu"
[2] "/tmp/RtmpikpfqI/renv-system-library"                                                       
> renv::deactivate()

Restarting R session...

> .libPaths()
[1] "/home/bureau.si.interne/dervieuxchr/testR/test-renv/renv/library/R-3.5/x86_64-pc-linux-gnu"
[2] "/applis/R/site-library/x86_64-pc-linux-gnu/3.5.1"                                          
[3] "/opt/R/3.5.1/lib64/R/library"    
```

Note that I close the RStudio project, and reopen it, the renv lib is not activated and the correct user library is set. 

I am on R 3.5.1 with `renv` 0.7.1.20 on RStudio Server Pro 1.2.1335-1

**Comment by kevinushey** [comment]
Should be fixed up now. Thanks for reporting!

**Comment by evasgit** [comment]
@kevinushey hi, it still happen on version 0.9.3-30. pls fix it, thx a lot.
R 3.5.1 with `renv 0.9.3`

**Comment by kevinushey** [comment]
Thanks for the report -- should be fixed on master now.
