### ISSUE TITLE
System libraries search on macos

### ISSUE THREAD

**Issue by nickflour** [rstudio/renv#704]
Hello all! It looks like that on my macos the search location for `include` libraries differ whether we are using renv or not. Please refer also to this mine [SO question](https://stackoverflow.com/questions/66908384/installing-sf-package-in-r-under-renv-on-macos). 

With renv:

```
> system("echo | gcc -Wp,-v -x c++ - -fsyntax-only", intern=TRUE)
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin19.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

Without renv:

```
> system("echo | gcc -Wp,-v -x c++ - -fsyntax-only", intern=TRUE)
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin19.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

Notice in particular that `/usr/local/include` is missing under renv. How can I fix it and have the same search path regardless of renv? Thank you

EDIT:

It looks like that simply loading renv changes the behaviour of the compiler. Here what happens on my installation on a fresh R session (no renv project):

```
> system("echo | gcc -Wp,-v -x c++ - -fsyntax-only", intern=TRUE)
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin19.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include ###ADDITION BY OP: THIS PATH IS PRESENT#####
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
character(0)
> require(renv)
Loading required package: renv

Attaching package: ‘renv’

The following object is masked from ‘package:stats’:

    update

The following objects are masked from ‘package:utils’:

    history, upgrade

The following objects are masked from ‘package:base’:

    load, remove

> system("echo | gcc -Wp,-v -x c++ - -fsyntax-only", intern=TRUE)
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin19.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here: ####ADDITION BY OP: No /usr/local/include
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.

```

**Comment by kevinushey** [comment]
That is very weird! I do not have a good idea what is going on here. At least, I cannot reproduce on my macOS machine; `/usr/local/include` is never included on the default search paths regardless of whether `renv` is activated or not.

Can you confirm that `Sys.which("gcc")` points to the same `gcc` in each case?

The only other thing I can think of is the `CPATH` environment variable being different; e.g.

```
> system("echo | CPATH=/usr/local/include gcc -Wp,-v -x c++ - -fsyntax-only", intern = TRUE)
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin20.3.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

**Comment by kevinushey** [comment]
I see now from https://stackoverflow.com/questions/66908384/installing-sf-package-in-r-under-renv-on-macos that you traced it to the `SDKROOT` environment variable. `renv` sets that here:

https://github.com/rstudio/renv/blob/2f0803f7bfe32737943f218443b8581ba90d0683/R/envvars.R#L57-L69

in an attempt to help older versions of R find where command line tools live.

**Comment by nickflour** [comment]
Hello Kevin, you are right, it looks like that setting `SDKROOT` is the cause of the issue. I solved by exporting it in my `bash_profile` with a blank value, so that renv, as you outlined, does not overwrite it. I'm not sure it's a safe solution, but now I am able to install packages that rely on libraries in `/usr/local` under renv. Some points: 1) Is it really needed for renv to set that variable? It looks like very invasive and, maybe, if it is not set there is a reason; 2) the issue I faced apparently was a combination of this setting by renv and the sf R package which looks like to have a bug, in the sense that, when checking for the presence of the header `proj.h`, does not pass to it the `--with-proj-include` configure arg, and that's pretty strange; 3) do you have some pointers for me to understand why I have `/usr/local/include` in the search path by default? For the record, in trying to have the best R installation, I tried the macos package, next the brew installation and, finally, I built it from source. I will remove the brew installation and keep the macos one just because I don't think there will be any conflict. For the reason why I did it, part of it was that I couldn't install some packages with renv and other part because of [this behaviour](https://stackoverflow.com/questions/66765784/showing-function-arguments-in-order-in-an-r-shell), which annoyed me a lot.

Thank you very much for your time and reply.

**Comment by hadley** [comment]
Since this is over two years old, it sounds like you have a solution (use the sf binary), and we haven't had other reports of this problem, I'm going to close. But the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
