### ISSUE TITLE
Incompatible architecture problem when installing new package

### ISSUE THREAD

**Issue by johannesnicolaus** [rstudio/renv#879]
Hi, 
I got an error which I suggest is due to my system, I am using an M1 macbook pro. I got this error when I wanted to install devtools and also igraph (I'm not sure if other packages also show similar error) using the command below. This error did not show when I tried to install the package outside of renv. 

```R
install.packages("devtools")
install.packages("igraph", type = "source")
```

Below is the error message that was shown
```
Error: package or namespace load failed for ‘commonmark’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/nico/test/erna_analysis/renv/staging/1/00LOCK-commonmark/00new/commonmark/libs/commonmark.so':
  dlopen(/Users/nico/test/erna_analysis/renv/staging/1/00LOCK-commonmark/00new/commonmark/libs/commonmark.so, 0x0006): tried: '/Users/nico/test/erna_analysis/renv/staging/1/00LOCK-commonmark/00new/commonmark/libs/commonmark.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/commonmark.so' (no such file), '/usr/lib/commonmark.so' (no such file)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/nico/test/erna_analysis/renv/staging/1/commonmark’
```

Previous to doing this, I installed gcc compiler using brew:

```shell
brew install gcc
```

and modified the ~/.R/Makevars file:

```
 CC = /opt/homebrew/bin/gcc-11
 CXX = /opt/homebrew/bin/g++-11
 FC = /opt/homebrew/bin/gfortran-11
 F77 = /opt/homebrew/bin/gfortran-11
 FLIBS = -L//opt/homebrew/lib/gcc/ -lgfortran -lm 
```
Could this have been the problem? Before, I wasn't able to install igraph due to problems with the gcc compiler.

Any help would be appreciated!

**Comment by kevinushey** [comment]
>   dlopen(/Users/nico/test/erna_analysis/renv/staging/1/00LOCK-commonmark/00new/commonmark/libs/commonmark.so, 0x0006): tried: '/Users/nico/test/erna_analysis/renv/staging/1/00LOCK-commonmark/00new/commonmark/libs/commonmark.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/commonmark.so' (no such file), '/usr/lib/commonmark.so' (no such file)

This error message is basically saying that your compiler is producing x86_64 libraries, but you're using an arm64 build of R and so that library cannot be successfully loaded.

My guess is that you need to tell `gcc` to produce arm64 libraries / executables.

That said -- why not just use system clang?

**Comment by kevinushey** [comment]
One other possibility... are you using RStudio, by any chance? What does `system("uname -m")` report for you?

**Comment by johannesnicolaus** [comment]
Hi @kevinushey , thanks for the reply!

> My guess is that you need to tell `gcc` to produce arm64 libraries / executables.

I'm really new to this and I don't really understand how to change this... Do I change this within R?

> That said -- why not just use system clang?

It did not work when I wanted to install the package igraph, which is why I changed to gcc

> One other possibility... are you using RStudio, by any chance? What does system("uname -m") report for you?

Yes I'm using RStudio, it reports x86_64 on system("uname -m"), so I'm guessing it detects the system as being x86_64 instead of arm64? Would it be better to reinstall R?

**Comment by kevinushey** [comment]
This sounds like an issue resolved in the latest version of RStudio -- can you try upgrading?

**Comment by johannesnicolaus** [comment]
Unfortunately, upgrading Rstudio did not solve the issue

There is still the following error messsage:
```
ld: warning: ignoring file /Library/Frameworks/R.framework/Resources/lib/libRlapack.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Library/Frameworks/R.framework/Resources/lib/libRblas.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Library/Frameworks/R.framework/R, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
Could there be some discrepancies between R settings and the installer within renv? especially because installation outside renv worked ok

I have also updated ~/.R/Makevars to the following after installing gfortran from here https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11-arm-alpha2 as I thought the installation from brew might have been the problem
```
 CC = /usr/local/gfortran/bin/gcc
 CXX = /usr/local/gfortran/bin/g++
 FC = /usr/local/gfortran/bin/gfortran
 F77 = /usr/local/gfortran/bin/gfortran
 FLIBS =  -L/usr/local/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0 -L/    usr/local/gfortran/lib -lgfortran -lm
```

**Comment by johannesnicolaus** [comment]
Hi, I tried to uninstall x86_64 R and installed the arm64 version using homebrew. Running from terminal using renv it worked, so I'm sure it has something to do with this. 

However, after changing to arm64 R, RStudio showed error upon launching:

```
dyld[11750]: terminating because inserted dylib '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib' could not be loaded: tried: '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/nico/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T/rstudio-fallback-library-path-5tOMek/libR.dylib' (no such file)
dyld[11750]: tried: '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/nico/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T/rstudio-fallback-library-path-5tOMek/libR.dylib' (no such file)
```
Is it possible that RStudio is somehow looking for the x86_64 R?

**Comment by johannesnicolaus** [comment]
Update:

I figured that the problem is probably because the previous installation of x86_64 R

I did the following commands from https://community.rstudio.com/t/rstudio-and-r-will-not-start-on-mac-m1-os-x-monterey/120055/3
:
```shell 
cd /Applications/Rstudio.app/Contents/MacOS
mv rsession rsession-x86
ln -s rsession-arm64 rsession
```


However, I now get the following error when installing some other packages within renv:

```shell
ld: warning: ignoring file init.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/gettext/lib/libintl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

Seems like I'm back to square one..

**Comment by kevinushey** [comment]
This is pretty surprising to me... on startup, RStudio tries to figure out the architecture of R by using something like:

```
file /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib
```

so it would seem like that check is failing, for some reason. Can you confirm what that reports for you? Can you also share the output of:

```
str(.Platform)
Sys.info()[["machine"]]
system("arch")
system("uname -m")
```

Do you have any better luck if you launch RStudio from a terminal, e.g. with:

```
RSTUDIO_WHICH_R=/opt/homebrew/bin/R /Applications/RStudio.app/Contents/MacOS/RStudio
```

Perhaps related -- how are you launching RStudio? Just via Spotlight, or something else?

A couple other users have bumped into this problem and I'd love to be able to get to the bottom of it.

**Comment by johannesnicolaus** [comment]
```shell
file /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib
```

Reports
```
/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libR.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

And here are the outputs for the subsequent commands:
```
> str(.Platform)
List of 8
 $ OS.type   : chr "unix"
 $ file.sep  : chr "/"
 $ dynlib.ext: chr ".so"
 $ GUI       : chr "RStudio"
 $ endian    : chr "little"
 $ pkgType   : chr "source"
 $ path.sep  : chr ":"
 $ r_arch    : chr ""
```
```
> Sys.info()[["machine"]]
[1] "arm64"
```
```
> system("arch")
i386> system("uname -m")
x86_64
```

Launching Rstudio using the following command results in the same error message. 
```
RSTUDIO_WHICH_R=/opt/homebrew/bin/R /Applications/RStudio.app/Contents/MacOS/RStudio
```

> Perhaps related -- how are you launching RStudio? Just via Spotlight, or something else?

Yes I am launching RStudio via Spotlight or from the applications folder in finder.

Could this be due to installation of R through brew? I found that when installing another package after switching from brew R to R downloaded from the R website (arm64 version) I got a different error message: 

```
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
```

I'm guessing some packages can't be installed using x86_64 and some packages can't be installed using arm64 but I might be wrong...

**Comment by kevinushey** [comment]
The fact that you're still seeing the wrong architecture in `system("arch")` is most likely the problem here, but I'm having trouble understanding why that's happening. For example, I see:

```
> system("arch")
arm64
> system("uname -m")
arm64
```

and this is with Homebrew R:

```
> R.home()
[1] "/opt/homebrew/Cellar/r/4.1.2/lib/R"
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20.6.0 (64-bit)
Running under: macOS Monterey 12.0.1
```

And this is even with a "regular" R installation at /Library/Frameworks/R.framework.

What do you see with the following -- do these work?

```
system("arch -arm64 /bin/sh -c arch")
system("arch -x86_64 /bin/sh -c arch")
```

**Comment by johannesnicolaus** [comment]
Thanks for the reply.

Yes, I'm not sure why this is happening either.

I see the following:
```
> system("arch")
i386
> system("uname -m")
x86_64
```

**Comment by kevinushey** [comment]
A diagnostics report might also be useful:

```
/Applications/RStudio.app/Contents/MacOS/RStudio --run-diagnostics
```

Finally ... I'd be curious to know if you see the same behavior outside of RStudio; e.g. if you're running R in the terminal or something else.

**Comment by johannesnicolaus** [comment]
Here is the diagnostics report:

```

RStudio Diagnostics Report
==========================

WARNING: This report may contain sensitive security information and / or
personally identifiable information. Please audit the below and redact any
sensitive information before submitting your diagnostics report.

Generated: Mon Dec  6 14:28:19 2021

RStudio Version
--------------------------------------------------
2021.09.1+372


Session Information
--------------------------------------------------
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin21.1.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2   


System Information
--------------------------------------------------
sysname        : Darwin                                                                                              
release        : 21.1.0                                                                                              
version        : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
nodename       : MacBook-Pro.local                                                                                   
machine        : arm64                                                                                               
login          : nico                                                                                                
user           : nico                                                                                                
effective_user : nico                                                                                                


Platform Information
--------------------------------------------------
OS.type    : unix
file.sep   : /
dynlib.ext : .so
GUI        : unknown
endian     : little
pkgType    : source
path.sep   : :
r_arch     : 


Environment Variables
--------------------------------------------------
_                             : /Applications/RStudio.app/Contents/MacOS/RStudio
__CF_USER_TEXT_ENCODING       : 0x1F5:0x0:0x0
__CFBundleIdentifier          : com.apple.Terminal
_P9K_TTY                      : /dev/ttys000
CLICOLOR_FORCE                : 1
DISPLAY                       : /private/tmp/com.apple.launchd.StZ9y9syZz/org.xquartz:0
DYLD_FALLBACK_LIBRARY_PATH    : /opt/homebrew/Cellar/r/4.1.2/lib/R/lib:/Users/nico/lib:/usr/local/lib:/usr/lib:/lib:/var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T/rstudio-fallback-library-path-GkkhK3
EDITOR                        : vi
GIT_ASKPASS                   : rpostback-askpass
HOME                          : /Users/nico
HOMEBREW_CELLAR               : /opt/homebrew/Cellar
HOMEBREW_PREFIX               : /opt/homebrew
HOMEBREW_REPOSITORY           : /opt/homebrew
HOMEBREW_SHELLENV_PREFIX      : /opt/homebrew
INFOPATH                      : /opt/homebrew/share/info:
LANG                          : en_US.UTF-8
LC_CTYPE                      : en_US.UTF-8
LESS                          : -R
LN_S                          : ln -s
LOGNAME                       : *** redacted ***
LSCOLORS                      : Gxfxcxdxbxegedabagacad
MAKE                          : make
MANPATH                       : /opt/homebrew/share/man::
OLDPWD                        : /Users/nico
P9K_SSH                       : 0
P9K_TTY                       : old
PAGER                         : less
PATH                          : /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/RStudio.app/Contents/MacOS/postback
PWD                           : *** redacted ***
PYTHONIOENCODING              : utf-8
R_BROWSER                     : /usr/bin/open
R_BZIPCMD                     : /usr/bin/bzip2
R_DOC_DIR                     : /opt/homebrew/Cellar/r/4.1.2/lib/R/doc
R_GZIPCMD                     : /usr/bin/gzip
R_HOME                        : /opt/homebrew/Cellar/r/4.1.2/lib/R
R_INCLUDE_DIR                 : /opt/homebrew/Cellar/r/4.1.2/lib/R/include
R_LIBS_SITE                   : 
R_LIBS_USER                   : ~/Library/R/arm64/4.1/library
R_PAPERSIZE                   : a4
R_PDFVIEWER                   : /usr/bin/open
R_PLATFORM                    : aarch64-apple-darwin21.1.0
R_PRINTCMD                    : lpr
R_RD4PDF                      : times,inconsolata,hyper
R_SESSION_TMPDIR              : /var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T//RtmpN30T8n
R_SHARE_DIR                   : /opt/homebrew/Cellar/r/4.1.2/lib/R/share
R_STRIP_SHARED_LIB            : strip -x
R_STRIP_STATIC_LIB            : strip -S
R_SYSTEM_ABI                  : macos,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD                 : /usr/bin/texi2dvi
R_UNZIPCMD                    : /usr/bin/unzip
R_ZIPCMD                      : /usr/bin/zip
RMARKDOWN_MATHJAX_PATH        : /Applications/RStudio.app/Contents/Resources/resources/mathjax-27
RS_PPM_FD_READ                : 13
RS_PPM_FD_WRITE               : 14
RS_RPOSTBACK_PATH             : /Applications/RStudio.app/Contents/MacOS/rpostback
RS_SHARED_SECRET              : *** redacted ***
RSTUDIO                       : 1
RSTUDIO_CONSOLE_COLOR         : 256
RSTUDIO_CONSOLE_WIDTH         : 80
RSTUDIO_FALLBACK_LIBRARY_PATH : /var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T/rstudio-fallback-library-path-GkkhK3
RSTUDIO_PANDOC                : /Applications/RStudio.app/Contents/MacOS/pandoc
RSTUDIO_PROGRAM_MODE          : desktop
RSTUDIO_SESSION_PORT          : 46150
RSTUDIO_USER_IDENTITY         : nico
RSTUDIO_WINUTILS              : bin/winutils
SED                           : /usr/bin/sed
SHELL                         : /bin/zsh
SHLVL                         : 1
SSH_ASKPASS                   : rpostback-askpass
SSH_AUTH_SOCK                 : *** redacted ***
TAR                           : /usr/bin/tar
TERM                          : xterm-256color
TERM_PROGRAM                  : Apple_Terminal
TERM_PROGRAM_VERSION          : 443
TERM_SESSION_ID               : E89F5A9A-9EC4-4D41-BCEE-1BDDEB742B2D
TMPDIR                        : /var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T/
USER                          : nico
XPC_FLAGS                     : 0x0
XPC_SERVICE_NAME              : 0
ZSH                           : /Users/nico/.oh-my-zsh


R Version
--------------------------------------------------
platform       : aarch64-apple-darwin21.1.0
arch           : aarch64
os             : darwin21.1.0
system         : aarch64, darwin21.1.0
status         : 
major          : 4
minor          : 1.2
year           : 2021
month          : 11
day            : 01
svn rev        : 81115
language       : R
version.string : R version 4.1.2 (2021-11-01)
nickname       : Bird Hippie


R Home
--------------------------------------------------
/opt/homebrew/Cellar/r/4.1.2/lib/R


R Search Path
--------------------------------------------------
.GlobalEnv       
tools:rstudio    
package:stats    
package:graphics 
package:grDevices
package:utils    
package:datasets 
package:methods  
Autoloads        
package:base     


R Library Paths
--------------------------------------------------
/opt/homebrew/lib/R/4.1/site-library      
/opt/homebrew/Cellar/r/4.1.2/lib/R/library


Loaded Packages
--------------------------------------------------
base      : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/base     
compiler  : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/compiler 
datasets  : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/datasets 
graphics  : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/graphics 
grDevices : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/grDevices
methods   : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/methods  
stats     : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/stats    
tools     : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/tools    
utils     : /opt/homebrew/Cellar/r/4.1.2/lib/R/library/utils    


Installed Packages
--------------------------------------------------
      Package                                    LibPath Version
1        base /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
2        boot /opt/homebrew/Cellar/r/4.1.2/lib/R/library  1.3-28
3       class /opt/homebrew/Cellar/r/4.1.2/lib/R/library  7.3-19
4     cluster /opt/homebrew/Cellar/r/4.1.2/lib/R/library   2.1.2
5   codetools /opt/homebrew/Cellar/r/4.1.2/lib/R/library  0.2-18
6    compiler /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
7    datasets /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
8     foreign /opt/homebrew/Cellar/r/4.1.2/lib/R/library  0.8-81
9    graphics /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
10  grDevices /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
11       grid /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
12 KernSmooth /opt/homebrew/Cellar/r/4.1.2/lib/R/library 2.23-20
13    lattice /opt/homebrew/Cellar/r/4.1.2/lib/R/library 0.20-45
14       MASS /opt/homebrew/Cellar/r/4.1.2/lib/R/library  7.3-54
15     Matrix /opt/homebrew/Cellar/r/4.1.2/lib/R/library   1.3-4
16    methods /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
17       mgcv /opt/homebrew/Cellar/r/4.1.2/lib/R/library  1.8-38
18       nlme /opt/homebrew/Cellar/r/4.1.2/lib/R/library 3.1-153
19       nnet /opt/homebrew/Cellar/r/4.1.2/lib/R/library  7.3-16
20   parallel /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
21      rpart /opt/homebrew/Cellar/r/4.1.2/lib/R/library  4.1-15
22    spatial /opt/homebrew/Cellar/r/4.1.2/lib/R/library  7.3-14
23    splines /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
24      stats /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
25     stats4 /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
26   survival /opt/homebrew/Cellar/r/4.1.2/lib/R/library  3.2-13
27      tcltk /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
28      tools /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2
29      utils /opt/homebrew/Cellar/r/4.1.2/lib/R/library   4.1.2


R System Profile: /opt/homebrew/Cellar/r/4.1.2/lib/R/library/base/R/Rprofile
--------------------------------------------------
### This is the system Rprofile file. It is always run on startup.
### Additional commands can be placed in site or user Rprofile files
### (see ?Rprofile).

### Copyright (C) 1995-2020 The R Core Team

### Notice that it is a bad idea to use this file as a template for
### personal startup files, since things will be executed twice and in
### the wrong environment (user profiles are run in .GlobalEnv).

.GlobalEnv <- globalenv()
attach(NULL, name = "Autoloads")
.AutoloadEnv <- as.environment(2)
assign(".Autoloaded", NULL, envir = .AutoloadEnv)
T <- TRUE
F <- FALSE
R.version <- structure(R.Version(), class = "simple.list")
version <- R.version            # for S compatibility

## for backwards compatibility only
R.version.string <- R.version$version.string

## NOTA BENE: options() for non-base package functionality are in places like
##            --------- ../utils/R/zzz.R

options(keep.source = interactive())
options(warn = 0)
# options(repos = c(CRAN="@CRAN@"))
# options(BIOC = "http://www.bioconductor.org")

## setting from an env variable added in 4.0.2
local({to <- as.integer(Sys.getenv("R_DEFAULT_INTERNET_TIMEOUT", 60))
    if (is.na(to) || to <= 0) to <- 60L
    options(timeout = to)
})
options(encoding = "native.enc")
options(show.error.messages = TRUE)
## keep in sync with PrintDefaults() in  ../../main/print.c :
options(scipen = 0)
options(max.print = 99999)# max. #{entries} in internal printMatrix()
options(add.smooth = TRUE)# currently only used in 'plot.lm'

if(isFALSE(as.logical(Sys.getenv("_R_OPTIONS_STRINGS_AS_FACTORS_",
                                 "FALSE")))) {
    options(stringsAsFactors = FALSE)
} else {
    options(stringsAsFactors = TRUE)
}

if(!interactive() && is.null(getOption("showErrorCalls")))
    options(showErrorCalls = TRUE)

local({dp <- Sys.getenv("R_DEFAULT_PACKAGES")
       if(identical(dp, "")) ## it fact methods is done first
           dp <- c("datasets", "utils", "grDevices", "graphics",
                   "stats", "methods")
       else if(identical(dp, "NULL")) dp <- character(0)
       else dp <- strsplit(dp, ",")[[1]]
       dp <- sub("[[:blank:]]*([[:alnum:]]+)", "\\1", dp) # strip whitespace
       options(defaultPackages = dp)
    })

## Expand R_LIBS_* environment variables.
Sys.setenv(R_LIBS_SITE =
           .expand_R_libs_env_var(Sys.getenv("R_LIBS_SITE")))
Sys.setenv(R_LIBS_USER =
           .expand_R_libs_env_var(Sys.getenv("R_LIBS_USER")))

local({
    if(nzchar(tl <- Sys.getenv("R_SESSION_TIME_LIMIT_CPU")))
        setSessionTimeLimit(cpu = tl)
    if(nzchar(tl <- Sys.getenv("R_SESSION_TIME_LIMIT_ELAPSED")))
        setSessionTimeLimit(elapsed = tl)
})

.First.sys <- function()
{
    for(pkg in getOption("defaultPackages")) {
        res <- require(pkg, quietly = TRUE, warn.conflicts = FALSE,
                       character.only = TRUE)
        if(!res)
            warning(gettextf('package %s in options("defaultPackages") was not found', sQuote(pkg)),
                    call. = FALSE, domain = NA)
    }
}

## called at C level in the startup process prior to .First.sys
.OptRequireMethods <- function()
{
    pkg <- "methods" # done this way to avoid R CMD check warning
    if(pkg %in% getOption("defaultPackages"))
        if(!require(pkg, quietly = TRUE, warn.conflicts = FALSE,
                    character.only = TRUE))
            warning('package "methods" in options("defaultPackages") was not found',
                    call. = FALSE)
}

if(nzchar(Sys.getenv("R_BATCH"))) {
    .Last.sys <- function()
    {
        cat("> proc.time()\n")
        print(proc.time())
    }
    ## avoid passing on to spawned R processes
    ## A system has been reported without Sys.unsetenv, so try this
    try(Sys.setenv(R_BATCH=""))
}

local({
    if(nzchar(rv <- Sys.getenv("_R_RNG_VERSION_")))
        suppressWarnings(RNGversion(rv))
})

.sys.timezone <- NA_character_
.First <- NULL
.Last <- NULL
###-*- R -*- Unix Specific ----

.Library <- file.path(R.home(), "library")
.Library.site <- Sys.getenv("R_LIBS_SITE")
.Library.site <- if(!nzchar(.Library.site)) file.path(R.home(), "site-library") else unlist(strsplit(.Library.site, ":"))
.Library.site <- .Library.site[file.exists(.Library.site)]

invisible(.libPaths(c(unlist(strsplit(Sys.getenv("R_LIBS"), ":")),
                      unlist(strsplit(Sys.getenv("R_LIBS_USER"), ":")
                      ))))
local({
    popath <- Sys.getenv("R_TRANSLATIONS", "")
    if(!nzchar(popath)) {
        paths <- file.path(.libPaths(), "translations", "DESCRIPTION")
        popath <- dirname(paths[file.exists(paths)][1])
    }
    bindtextdomain("R", popath)
    bindtextdomain("R-base", popath)
    assign(".popath", popath, .BaseNamespaceEnv)
})
local({
## we distinguish between R_PAPERSIZE as set by the user and by configure
papersize <- Sys.getenv("R_PAPERSIZE_USER")
if(!nchar(papersize)) {
    lcpaper <- Sys.getlocale("LC_PAPER") # might be null: OK as nchar is 0
    papersize <- if(nchar(lcpaper))
        if(length(grep("(_US|_CA)", lcpaper))) "letter" else "a4"
    else Sys.getenv("R_PAPERSIZE")
}
options(papersize = papersize,
        printcmd = Sys.getenv("R_PRINTCMD"),
        dvipscmd = Sys.getenv("DVIPS", "dvips"),
        texi2dvi = Sys.getenv("R_TEXI2DVICMD"),
        browser = Sys.getenv("R_BROWSER"),
        pager = file.path(R.home(), "bin", "pager"),
        pdfviewer = Sys.getenv("R_PDFVIEWER"),
        useFancyQuotes = TRUE)
})

## non standard settings for the R.app GUI of the macOS port
if(.Platform$GUI == "AQUA") {
    ## this is set to let RAqua use both X11 device and X11/TclTk
    if (Sys.getenv("DISPLAY") == "")
	Sys.setenv("DISPLAY" = ":0")

    ## this is to allow gfortran compiler to work
    Sys.setenv("PATH" = paste(Sys.getenv("PATH"),":/usr/local/bin",sep = ""))
}## end "Aqua"

## de-dupe the environment on macOS (bug in Yosemite which affects things like PATH)
if (grepl("^darwin", R.version$os)) local({
    ## we have to de-dupe one at a time and re-check since the bug affects how
    ## environment modifications propagate
    while(length(dupes <- names(Sys.getenv())[table(names(Sys.getenv())) > 1])) {
        env <- dupes[1]
        value <- Sys.getenv(env)
        Sys.unsetenv(env)             ## removes the dupes, good
        .Internal(Sys.setenv(env, value)) ## wrapper requries named vector, a pain, hence internal
    }
})

local({
    tests_startup <- Sys.getenv("R_TESTS")
    if(nzchar(tests_startup)) source(tests_startup)
})


R Site Profile: /opt/homebrew/Cellar/r/4.1.2/lib/R/etc/Rprofile.site
--------------------------------------------------
(File does not exist)


R User Profile: /Users/nico/.Rprofile
--------------------------------------------------
(File does not exist)


R Site Environ: /opt/homebrew/Cellar/r/4.1.2/lib/R/etc/Renviron.site
--------------------------------------------------
(File does not exist)


R User Environ: /Users/nico/.Renviron
--------------------------------------------------
(File does not exist)


R Temporary Directory
--------------------------------------------------
/var/folders/1j/krv4k2fn3f519h0pcs31lxgw0000gn/T//RtmpN30T8n


Files in R Temporary Directory
--------------------------------------------------
rs-graphics-23a69242-5368-4072-ac19-c56cf65b2488


Log file: /Users/nico/.local/share/rstudio/log/rdesktop.log
--------------------------------------------------

(Not Found)

Log file: /Users/nico/.local/share/rstudio/log/rsession-nico.log
--------------------------------------------------

2021-12-06T01:30:35.869443Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:35.869443Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:35.870783Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T01:30:35.870783Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T01:30:36.076145Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:36.076145Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:36.076941Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T01:30:36.076941Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T01:30:36.282406Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:36.282406Z [rsession-nico] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-12-06T01:30:36.282887Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T01:30:36.282887Z [rsession-nico] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T02:31:49.127972Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T02:31:49.127972Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T02:42:32.646738Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T02:42:32.646738Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T03:31:51.825376Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T03:31:51.825376Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T03:59:55.961365Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T03:59:55.961365Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T04:43:10.714826Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
2021-12-06T04:43:10.714826Z [rsession-nico] ERROR CLIENT EXCEPTION (rsession-nico): (TypeError) : Cannot read property 'parentNode' of null;|||com/google/gwt/dom/client/DOMImpl.java#253::getParentElement|||com/google/gwt/dom/client/Node.java#189::getParentElement|||org/rstudio/core/client/widget/RStudioDataGrid.java#63::hideMacHorizontalScrollbars|||org/rstudio/core/client/widget/RStudioDataGrid.java#60::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36


User prefs: /Users/nico/.config/rstudio/rstudio-prefs.json
--------------------------------------------------

{
    "initial_working_directory": "~",
    "editor_theme": "Monokai",
    "posix_terminal_shell": "bash",
    "jobs_tab_visibility": "shown"
}

System prefs: /etc/rstudio/rstudio-prefs.json
--------------------------------------------------

(Not Found)

User state: /Users/nico/.local/share/rstudio/rstudio-desktop.json
--------------------------------------------------

{
    "context_id": "4E5D2568",
    "theme": {
        "name": "Monokai",
        "url": "theme/default/monokai.rstheme",
        "isDark": true
    },
    "error_handler_type": "traceback"
}


```

For the same package (fastmap) I found that installation succeeded within renv in R from terminal. 

However, I am getting some other errors for other packages which I did not get when I used x86_64 (well this might be another unrelated issue to renv I guess)

**Comment by kevinushey** [comment]
Thanks! I still don't see anything relevant, though :-/

I've re-opened https://github.com/rstudio/rstudio/issues/9543 for now.

**Comment by kevinushey** [comment]
Ultimately, I believe this is an RStudio issue, not an `renv` one, so let's try to continue the discussion in https://github.com/rstudio/rstudio/issues/9543 -- thanks!
